name: GithubActions Test

on: 
  push: 
    branches : 
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkRoot
      run: pwd
    - name: ls -al
      run : ls -al
    - name: check disk
      run : df -h
    
        
    
